-- Exported by JKG Dialogue Creator

DLG.Name = "test_trooper"
DLG.RootNode = "E1"
DLG.Nodes = {
	E1 = {
		Type = 1,
		SubNode = "T2",
		HasCondition = false,
	},
	T2 = {
		Type = 2,
		SubNode = "O4",
		Text = "Ha.  I must be hallucinating...you can't be real can you?",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	O4 = {
		Type = 3,
		SubNode = "T11",
		NextNode = "O8",
		Text = "I'm definitely real.",
		HasCondition = false,
		HasResolver = false,
	},
	T11 = {
		Type = 2,
		SubNode = "T12",
		Text = "That's just what a hallucination would say!",
		Duration = 2000,
		HasCondition = false,
		HasResolver = false,
	},
	T12 = {
		Type = 2,
		SubNode = "D13",
		Text = "I've got to find a way off this rock before I completely lose it...\nCome on Gary, they're not real.\nThe people AREN'T REAL!",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	D13 = {
		Type = 5,
	},
	O8 = {
		Type = 3,
		SubNode = "T14",
		NextNode = "O9",
		Text = "Just another Jedi mind trick I'm afraid...",
		HasCondition = false,
		HasResolver = false,
	},
	T14 = {
		Type = 2,
		SubNode = "T15",
		Text = "Of...course!  That's why it doesn't make any sense, there's a Jedi messing with my mind.",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	T15 = {
		Type = 2,
		SubNode = "D16",
		Text = "The Captain would have never left me alone here otherwise.\nGotta find that Jedi...",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D16 = {
		Type = 5,
	},
	O9 = {
		Type = 3,
		SubNode = "T17",
		NextNode = "O10",
		Text = "No, not at all.",
		HasCondition = false,
		HasResolver = false,
	},
	T17 = {
		Type = 2,
		SubNode = "O18",
		Text = "That's-wait...are you real?",
		Duration = 2000,
		HasCondition = false,
		HasResolver = false,
	},
	O18 = {
		Type = 3,
		SubNode = "T36",
		NextNode = "O19",
		Text = "[Force Persuade] I am.",
		HasCondition = false,
		HasResolver = false,
	},
	T36 = {
		Type = 2,
		SubNode = "D37",
		Text = "^1FOR THE EMPEROR!",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D37 = {
		Type = 5,
	},
	O19 = {
		Type = 3,
		SubNode = "T38",
		NextNode = "O20",
		Text = "[Persuade] If I shoot you, will the pain convince you?",
		HasCondition = false,
		HasResolver = false,
	},
	T38 = {
		Type = 2,
		SubNode = "D39",
		Text = "^1FOR THE EMPIRE!",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D39 = {
		Type = 5,
	},
	O20 = {
		Type = 3,
		SubNode = "L21",
		Text = "Nevermind...",
		HasCondition = false,
		HasResolver = false,
	},
	L21 = {
		Type = 4,
		Target = "T12",
	},
	O10 = {
		Type = 3,
		SubNode = "T22",
		Text = "Snap out of it soldier and give me a report!",
		HasCondition = false,
		HasResolver = false,
	},
	T22 = {
		Type = 2,
		SubNode = "O23",
		Text = "Sir! The rebels are here they-wait, who are you?!",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	O23 = {
		Type = 3,
		SubNode = "T27",
		NextNode = "O24",
		Text = "A friend.",
		HasCondition = false,
		HasResolver = false,
	},
	T27 = {
		Type = 2,
		SubNode = "L28",
		Text = "I must be losing it.  A friend?  Out here?\nJ-ju-st hearing things...n-nothing real out here.",
		Duration = 4000,
		HasCondition = false,
		HasResolver = false,
	},
	L28 = {
		Type = 4,
		Target = "T12",
	},
	O24 = {
		Type = 3,
		SubNode = "T29",
		NextNode = "O25",
		Text = "The last person you'll ever see.",
		HasCondition = false,
		HasResolver = false,
	},
	T29 = {
		Type = 2,
		SubNode = "L35",
		Text = "No...no they're not real!  NONE OF YOU ARE REAL!",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	L35 = {
		Type = 4,
		Target = "T33",
	},
	O25 = {
		Type = 3,
		SubNode = "T30",
		NextNode = "O26",
		Text = "Your worst nightmare.",
		HasCondition = false,
		HasResolver = false,
	},
	T30 = {
		Type = 2,
		SubNode = "D31",
		Text = "I've seen worse.  At least you only have one mouth.  Gotta get some sleep...",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D31 = {
		Type = 5,
	},
	O26 = {
		Type = 3,
		SubNode = "T32",
		Text = "I'm you're commanding officer private!  Are you questioning me?",
		HasCondition = false,
		HasResolver = false,
	},
	T32 = {
		Type = 2,
		SubNode = "T33",
		Text = "No!  A trick of the enemy sent to confuse us.",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	T33 = {
		Type = 2,
		SubNode = "D34",
		Text = "IT WON'T WORK!  ^1IT WON'T WORK YOU HEAR ME!?",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D34 = {
		Type = 5,
	},
}
